DROP TABLE IF EXISTS chemotherapy_data;
CREATE TABLE chemotherapy_data(
	id serial,
	pseudonym varchar(20),
	patient_medication_id varchar(40),
	patient_cycle_id varchar(40),
	startday smallint,
	calculation_date date,
	calculated_bsa float,
	used_bsa float,
	serial_number smallint,
	cycle_id varchar(40),
	cycle_name varchar(255),
	cycle smallint,
	cycle_start_date date,
	cycle_end_date date,
	generic_name varchar(255),
	dose varchar(255),
	administration_serial_number smallint,
	administration_definition varchar(70),
	cycle_basic_dose float,
	cycle_dose_definition varchar(70),
	used_dose float,
	adminisitration_id varchar(18),
	administration_start_date date,
	administration_end_date date,
	height float,
	weight float
);